name: famelink
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.14+15

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_svg:
  marquee: ^2.2.0
  flutter_screenutil: ^5.1.1
#  modal_bottom_sheet: ^2.0.0
#  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_staggered_grid_view: ^0.4.1
  flutter_cache_manager: ^3.3.0
  #cached_video_player: ^2.0.4
  http: ^0.13.3
#  intl: ^0.17.0
  dio: ^4.0.0
  timeago: ^3.1.0
  readmore: ^2.0.0
#  flutter_widget_from_html:
#  camera: ^0.9.4+3
  camera: ^0.9.8
  hive:
#  otp_autofill: ^2.1.0
  decorated_icon: ^1.2.1
  webview_flutter: ^2.1.2
  path_provider: ^2.0.5
  path: ^1.8.1
  provider: ^6.0.5
#  provider: ^6.0.1
  socket_io_client: ^1.0.2
  google_sign_in:
  dotted_border: ^2.0.0+1
  uni_links: ^0.5.1
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_auth:
  firebase_messaging:
  flutter_local_notifications: ^9.1.5
  timezone: ^0.8.0
  flutter_typeahead: ^3.2.5
  video_player: ^2.4.2
#  visibility_aware_state: ^1.0.3
#  preload_page_view: ^0.1.6
  file_picker: ^4.1.3
  country_codes: ^2.0.1
  video_trimmer: ^1.1.3
  #flutter_ffmpeg: ^0.4.2
  video_compress: ^3.1.1
  flutter_speed_dial: ^5.0.0+1
#  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.7
  introduction_screen: ^2.1.0
  image_picker: ^0.8.3+3
  image_cropper: ^1.4.1
  image_crop: ^0.4.1
  flutter_image_compress: ^1.1.3
#  popover: ^0.2.6+2
  gender_picker: ^1.1.0
  group_button: ^3.3.1
  url_launcher: ^6.0.9
  drift: ^2.3.0
  rxdart: ^0.27.2
  showcaseview: ^1.1.4
  in_app_update: ^4.0.1
  pinch_zoom: ^1.0.0
  audioplayers: ^0.20.1
  connectivity: ^3.0.6
  #google_mobile_ads: ^1.1.0
  cached_network_image: ^3.2.0
  sign_in_with_apple: ^3.3.0
  firebase_crashlytics: ^3.0.6
  gradient_borders: ^0.2.0
#  inview_notifier_list: ^3.0.0
#  visibility_detector: ^0.2.2
  percent_indicator: ^4.0.0
#  liquid_progress_indicator: ^0.4.0
#  photofilters: ^3.0.1
  image: ^3.2.2
  google_ml_vision: ^0.0.7
#  helpers: ^1.1.4
  permission_handler: ^8.3.0
#  image_gallery_saver: ^1.7.1
  flutter_countdown_timer: ^4.1.0
#  better_player: ^0.0.81
  flutter_keychain: ^2.1.0
  flutter_easyloading: ^3.0.5
#  native_ads_flutter: ^1.0.7
  google_native_mobile_ads: ^1.0.3
  firebase_dynamic_links: ^5.0.17
#  cached_video_player:
#    path: ./flutter_cached_video_player
#  flutter_carousel_slider:
#  tiktoklikescroller:
#  clippy_flutter:
  double_back_to_close:
#  custom_radio_grouped_button:
  simple_speed_dial:
  group_radio_button:
  share_plus:
  facebook_app_events: ^0.19.0
  google_fonts: ^4.0.4
#  circular_profile_avatar:

    # Phase -2
  flutter_switch: ^0.3.2
  hexcolor: ^2.0.0
  get:
  dropdown_button2:
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0
  visibility_detector: ^0.3.3
  cloud_firestore_web: ^3.3.5
#  scroll_to_index:
#  dots_indicator:





dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.2.0+1
  build_runner: ^2.1.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/svg/
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: Poppins
  #      fonts:
  #        - asset: assets/fonts/Poppins-Light.ttf
  #          weight: 100
  #        - asset: assets/fonts/Poppins-Medium.ttf
  #          weight: 400
  #        - asset: assets/fonts/Poppins-Bold.ttf
  #          weight: 600
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
