///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddRatingResponseResult {
/*
{
  "_id": "63d8e3486c4b45c620ec218e",
  "trendId": "629f90e9ca89ce4c9ac6266a",
  "userId": "627a2673ebc6196471e3c347",
  "createdAt": "2023-01-31T09:45:43.744Z",
  "rating": 3,
  "updatedAt": "2023-01-31T10:38:20.848Z"
}
*/

  String? Id;
  String? trendId;
  String? userId;
  String? createdAt;
  int? rating;
  String? updatedAt;

  AddRatingResponseResult({
    this.Id,
    this.trendId,
    this.userId,
    this.createdAt,
    this.rating,
    this.updatedAt,
  });
  AddRatingResponseResult.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    trendId = json['trendId']?.toString();
    userId = json['userId']?.toString();
    createdAt = json['createdAt']?.toString();
    rating = json['rating']?.toInt();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['trendId'] = trendId;
    data['userId'] = userId;
    data['createdAt'] = createdAt;
    data['rating'] = rating;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class AddRatingResponse {
/*
{
  "result": {
    "_id": "63d8e3486c4b45c620ec218e",
    "trendId": "629f90e9ca89ce4c9ac6266a",
    "userId": "627a2673ebc6196471e3c347",
    "createdAt": "2023-01-31T09:45:43.744Z",
    "rating": 3,
    "updatedAt": "2023-01-31T10:38:20.848Z"
  },
  "message": "rating added successfully",
  "success": true
}
*/

  AddRatingResponseResult? result;
  String? message;
  bool? success;

  AddRatingResponse({
    this.result,
    this.message,
    this.success,
  });
  AddRatingResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? AddRatingResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['success'] = success;
    return data;
  }
}
